# Generated by Django 2.0 on 2018-08-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='google_plus',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='twitter',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
