# Generated by Django 2.0.1 on 2018-08-01 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_auto_20180801_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_discussion_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('assignment_discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Assignment_discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
