# Generated by Django 2.0 on 2018-10-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='image',
            field=models.ImageField(blank=True, upload_to='assignment_image//%Y/%m/%d/'),
        ),
    ]
