# Generated by Django 2.0 on 2018-08-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20180815_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsite',
            name='background_image',
            field=models.ImageField(upload_to='blogger_image/'),
        ),
    ]
