# Generated by Django 2.0 on 2019-01-16 05:11

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_assignment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_page',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='blog_page',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='blogsite',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='blogger_image/'),
        ),
        migrations.AlterField(
            model_name='blogsite',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
