# Generated by Django 2.0 on 2019-01-16 10:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment', '0003_auto_20190116_1041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogsite',
            new_name='Workbook',
        ),
        migrations.RenameModel(
            old_name='Blog_page',
            new_name='Workbook_page',
        ),
    ]
