# Generated by Django 2.0 on 2019-01-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20190116_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workbook_page',
            old_name='blog_site',
            new_name='workbook',
        ),
    ]
