# Generated by Django 2.0 on 2018-09-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_auto_20180922_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklet',
            name='document',
        ),
        migrations.AddField(
            model_name='booklet',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
