# Generated by Django 2.0 on 2018-09-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_auto_20180928_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklet',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booklet',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
