# Generated by Django 2.0 on 2018-09-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_auto_20180928_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklet',
            name='image',
            field=models.ImageField(blank=True, upload_to='booklet_image//%Y/%m/%d/'),
        ),
    ]
