# Generated by Django 2.0.1 on 2018-07-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0032_auto_20180731_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='number_of_like',
            field=models.IntegerField(default=0),
        ),
    ]
