# Generated by Django 2.0.1 on 2018-07-31 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0035_auto_20180731_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='like',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='number_of_like',
        ),
    ]
