# Generated by Django 2.0.1 on 2018-08-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0037_auto_20180808_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.ImageField(blank=True, upload_to='question_image//%Y/%m/%d/'),
        ),
    ]
